window._ = require 'lodash'
window.$ = require 'jquery'
window.moment = require 'moment'
window.Promise = require 'bluebird'
window.React = require 'react/addons'
window.ReactBootstrap = require 'react-bootstrap'
window.Backbone = require 'backbone'
